
welcome: "Welcome to Calculator! Enter your name: "
valid_name: "Make sure to use a valid name."
greeting: "Hi, #{name}!"
num_1: "What's the first number?"
num1_error: "Hmm...that doesn't look like a valid number."
num_2: "What's the second number?"
num2_error: "Hmm...that doesn't look like a valid number."
choice_error: "Must choose 1, 2, 3 or 4"
zero_div_error: "Can't divide by zero! Please choose operation 1, 2, or 3"
calculating: "#{operation_to_message(operator)} the two numbers..."
result: "The result is #{result}"
repeat: "Do you want to perform another calculation? (Y to calculate again)"
goodbye: "Thanks for using the calculator. Goodbye!"