welcome: "Let's play! Win 3 rounds to be declared Grand Winner!"
abbr_choices: "(You can abbreviate by choosing: r, p, s, l, sp)"
input_error: "That's not a valid choice."
replay: "Do you want to play again?"
goodbye: "Thank you for playing. Goodbye!"
win: "You won!"
lose: "Computer won!"
tie: "It's a tie!"
linebreak1: "-----------------------------------"
grandwinner: "You are the Grand Winner! Nice job!"
linebreak2: "----------------------------------------------------"
grandloser: "Computer is the Grand Winner! Better luck next time!"
