welcome: "Welcome to Mortgage Calculator!"
name_prompt: "Please enter your name:"
name_error: "Try again...use a valid name!"
loan_amount_prompt: "Please enter your loan amount in dollars. (For example, $100,000 should be entered as 100000):"
loan_amount_error: "Loan amount must be a valid number greater than 0. Don't use symbols (no '$' or ','). Try again."
apr_prompt: "Please enter your APR. Enter percentage in decimal format (for example, enter 5% as 0.05):"
apr_error1: "Something's wrong. Try re-entering your APR in the correct format."
apr_error2: "If you're not sure, divide percentage by 100: (5% / 100 = 0.05)"
loan_duration_prompt: "Please enter your loan duration in years:"
loan_duration_error: "That doesn't look right. Enter a valid number of years."
repeat_question: "Would you like to perform another calculation? Type 'y' or 'n'."
repeat_error: "Sorry, please enter 'y' or 'n'."
goodbye: "Thanks for using Mortgage Calculator!"